name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza con el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

  permissions:
  contents: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Cambia la versión de Ruby

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
        personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site

